name: Rodar Script para Alimentar Banco de Dados Neon

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout código
        uses: actions/checkout@v2

      # Passo 2: Configurar o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ou a versão que você estiver usando

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pg8000  # Instalar o pg8000 para conectar ao PostgreSQL
          
      # Passo 4: Rodar o script
      - name: Rodar o script
        env:
          NEON_DB_URL: ${{ secrets.NEON_DB_URL }}  # Passa o segredo da URL do banco de dados como variável de ambiente
        run: |
          python seu_script.py  # Substitua "seu_script.py" pelo nome do seu script Python
